#ifndef WEB_UI_H
#define WEB_UI_H

const char index_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"vi\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n"
"    <title>ESP32 OS Trackpad</title>\n"
"    <style>\n"
"        :root {\n"
"            --bg-color: #e0e5ec;\n"
"            --text-color: #4a5568;\n"
"            --shadow-light: #ffffff;\n"
"            --shadow-dark: #a3b1c6;\n"
"            --accent: #3b82f6;\n"
"        }\n"
"\n"
"        * { box-sizing: border-box; }\n"
"\n"
"        body, html {\n"
"            margin: 0; padding: 0; width: 100%; height: 100%;\n"
"            background-color: var(--bg-color);\n"
"            color: var(--text-color);\n"
"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
"            overflow: hidden;\n"
"            user-select: none;\n"
"            -webkit-user-select: none;\n"
"            display: flex; flex-direction: column;\n"
"        }\n"
"        \n"
"        #header {\n"
"            flex-shrink: 0;\n"
"            text-align: center; padding: 15px 20px; display: flex; justify-content: space-between; align-items: center; \n"
"            font-size: 18px; font-weight: bold; \n"
"            letter-spacing: 1px;\n"
"            color: var(--text-color);\n"
"            border-bottom: 1px solid rgba(0,0,0,0.05);\n"
"            background: var(--bg-color);\n"
"            z-index: 10;\n"
"        }\n"
"        \n"
"        #status { font-size: 12px; color: #718096; font-weight: normal; margin-left: 10px; }\n"
"\n"
"        .content-scrollable {\n"
"            flex: 1;\n"
"            overflow-y: auto;\n"
"            -webkit-overflow-scrolling: touch;\n"
"            padding: 20px;\n"
"            display: flex; flex-direction: column;\n"
"            gap: 25px;\n"
"        }\n"
"        \n"
"        .card {\n"
"            border-radius: 20px;\n"
"            background: var(--bg-color);\n"
"            box-shadow: \n"
"                6px 6px 12px var(--shadow-dark), \n"
"                -6px -6px 12px var(--shadow-light);\n"
"            padding: 20px;\n"
"        }\n"
"\n"
"        .trackpad-card {\n"
"            padding: 0;\n"
"            display: flex; justify-content: center; align-items: center;\n"
"            height: 300px;\n"
"            flex-shrink: 0;\n"
"            box-shadow: \n"
"                inset 6px 6px 12px var(--shadow-dark), \n"
"                inset -6px -6px 12px var(--shadow-light);\n"
"            position: relative;\n"
"            touch-action: none;\n"
"        }\n"
"        \n"
"        #trackpad-hint {\n"
"            color: rgba(74, 85, 104, 0.2);\n"
"            font-size: 32px; font-weight: bold;\n"
"            pointer-events: none;\n"
"            letter-spacing: 2px;\n"
"        }\n"
"        \n"
"        .buttons-grid {\n"
"            display: grid;\n"
"            grid-template-columns: 1fr 1fr;\n"
"            gap: 20px;\n"
"            padding: 5px;\n"
"        }\n"
"        \n"
"        .btn {\n"
"            background: var(--bg-color);\n"
"            border-radius: 16px;\n"
"            color: var(--text-color); \n"
"            font-size: 16px; font-weight: bold;\n"
"            height: 65px;\n"
"            display: flex; justify-content: center; align-items: center;\n"
"            cursor: pointer;\n"
"            box-shadow: \n"
"                6px 6px 12px var(--shadow-dark), \n"
"                -6px -6px 12px var(--shadow-light);\n"
"            transition: all 0.1s ease;\n"
"        }\n"
"\n"
"        .btn.full-width {\n"
"            grid-column: span 2;\n"
"        }\n"
"\n"
"        .btn.btn-colored {\n"
"            color: white;\n"
"            text-shadow: 1px 1px 2px rgba(0,0,0,0.1);\n"
"        }\n"
"        \n"
"        .btn:active {\n"
"            box-shadow: \n"
"                inset 4px 4px 8px var(--shadow-dark), \n"
"                inset -4px -4px 8px var(--shadow-light);\n"
"            color: var(--accent);\n"
"        }\n"
"        \n"
"        .chart-container {\n"
"            width: 100%; height: 220px;\n"
"            display: flex; justify-content: center; align-items: center;\n"
"            padding: 10px;\n"
"            flex-shrink: 0;\n"
"        }\n"
"    \n"
"        /* Settings Modal */\n"
"        .modal {\n"
"            display: none; position: fixed; z-index: 100;\n"
"            left: 0; top: 0; width: 100%; height: 100%;\n"
"            background-color: rgba(0,0,0,0.5);\n"
"            justify-content: center; align-items: center;\n"
"        }\n"
"        .modal-content {\n"
"            background-color: var(--bg-color);\n"
"            padding: 20px; border-radius: 20px;\n"
"            width: 90%; max-width: 400px;\n"
"            box-shadow: 6px 6px 12px var(--shadow-dark), -6px -6px 12px var(--shadow-light);\n"
"        }\n"
"        .modal-header { font-size: 20px; font-weight: bold; margin-bottom: 20px; text-align: center;}\n"
"        .setting-item {\n"
"            display: flex; justify-content: space-between; align-items: center;\n"
"            margin-bottom: 15px; padding-bottom: 15px; border-bottom: 1px solid rgba(0,0,0,0.05);\n"
"        }\n"
"        .switch { position: relative; display: inline-block; width: 50px; height: 26px; }\n"
"        .switch input { opacity: 0; width: 0; height: 0; }\n"
"        .slider {\n"
"            position: absolute; cursor: pointer; top: 0; left: 0; right: 0; bottom: 0;\n"
"            background-color: #ccc; transition: .4s; border-radius: 26px;\n"
"        }\n"
"        .slider:before {\n"
"            position: absolute; content: \"\"; height: 20px; width: 20px;\n"
"            left: 3px; bottom: 3px; background-color: white; transition: .4s; border-radius: 50%;\n"
"        }\n"
"        input:checked + .slider { background-color: var(--accent); }\n"
"        input:checked + .slider:before { transform: translateX(24px); }\n"
"        .close-btn {\n"
"            background: var(--accent); color: white; border: none; padding: 10px;\n"
"            width: 100%; border-radius: 10px; font-size: 16px; margin-top: 10px; cursor: pointer;\n"
"        }\n"
"    \n"
"        .dropdown { position: relative; display: inline-block; }\n"
"        .dropbtn { background-color: #3b82f6; color: white; padding: 8px 12px; font-size: 14px; border: none; border-radius: 6px; cursor: pointer; box-shadow: 0 4px 6px rgba(0,0,0,0.3); font-weight: bold; }\n"
"        .dropdown-content { display: none; position: absolute; right: 0; background-color: #1e293b; min-width: 160px; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.5); z-index: 100; border-radius: 8px; overflow: auto; margin-top: 5px; }\n"
"        .dropdown-content a { color: white; padding: 12px 16px; text-decoration: none; display: block; font-weight: bold; border-bottom: 1px solid #334155; font-size: 14px; }\n"
"        .dropdown-content a:hover { background-color: #334155; }\n"
"        .show { display: block; }\n"
"    </style>\n"
"    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n"
"</head>\n"
"<body>\n"
"    <div id=\"header\">\n"
"        <div style=\"text-align: left;\">\n"
"            <div>SMART OS <span id=\"status\">🔴 Chờ kết nối...</span></div>\n"
"            <div id=\"ram-info\" style=\"font-size: 13px; font-weight: normal; color: var(--accent); margin-top: 5px;\">RAM: Đang tải...</div>\n"
"        </div>\n"
"        <div class=\"dropdown\">\n"
"            <button onclick=\"document.getElementById('myDropdown').classList.toggle('show')\" class=\"dropbtn\">☰ Menu</button>\n"
"            <div id=\"myDropdown\" class=\"dropdown-content\">\n"
"                <a href=\"#\" onclick=\"openSettings()\">⚙️ Cài Đặt</a>\n"
"                <a href=\"#\" onclick=\"document.getElementById('terminal-modal').style.display='flex'\">💻 Terminal</a>\n"
"                <a href=\"#\" onclick=\"openFM()\">📁 File Manager</a>\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"    \n"
"    <main class=\"content-scrollable\">\n"
"        <div id=\"trackpad\" class=\"card trackpad-card\">\n"
"            <span id=\"trackpad-hint\">TRACKPAD</span>\n"
"        </div>\n"
"\n"
"        <div class=\"buttons-grid\">\n"
"            <div class=\"btn\" id=\"btn-click\">CLICK</div>\n"
"            <div class=\"btn\" id=\"btn-back\">BACK</div>\n"
"            <div class=\"btn full-width\" id=\"btn-wp\">W.PAPER</div>\n"
"            <div class=\"btn btn-colored\" id=\"btn-r1\" style=\"background: #eab308;\">ĐÈN (R1)</div>\n"
"            <div class=\"btn btn-colored\" id=\"btn-r2\" style=\"background: #9ca3af;\">R2 (TRỐNG)</div>\n"
"        </div>\n"
"\n"
"        <div class=\"card\" id=\"weather-card\" style=\"margin-bottom: 15px; font-size: 14px;\">\n"
"            <div style=\"font-weight: bold; margin-bottom: 5px; color: var(--accent);\">🌤 Thời tiết & AI Dự báo</div>\n"
"            <div id=\"weather-info\">Đang tải dữ liệu...</div>\n"
"        </div>\n"
"\n"
"        <div class=\"card chart-container\">\n"
"            <canvas id=\"dataChart\"></canvas>\n"
"        </div>\n"
"        \n"
"        <input type=\"file\" id=\"file-input\" accept=\"image/*\" style=\"display: none;\">\n"
"    </main>\n"
"\n"
"    <script>\n"
"        let ws;\n"
"        const statusEl = document.getElementById('status');\n"
"        const trackpad = document.getElementById('trackpad');\n"
"        const btnClick = document.getElementById('btn-click');\n"
"        const btnBack = document.getElementById('btn-back');\n"
"\n"
"        function triggerHaptic(duration = 15) {\n"
"            if (navigator.vibrate) {\n"
"                navigator.vibrate(duration);\n"
"            }\n"
"        }\n"
"\n"
"        function connectWs() {\n"
"            const gateway = `ws://${window.location.hostname}/ws`;\n"
"            ws = new WebSocket(gateway);\n"
"            \n"
"            ws.onopen = () => { statusEl.innerText = \"🟢 Đã kết nối\"; };\n"
"            ws.onclose = () => { statusEl.innerText = \"🔴 Mất kết nối\"; setTimeout(connectWs, 2000); };\n"
"            ws.onerror = () => { statusEl.innerText = \"⚠️ Lỗi WS\"; };\n"
"\n"
"            ws.onmessage = (e) => { \n"
"                try {\n"
"                    const d = JSON.parse(e.data);\n"
"                    if (d.type === 'log') {\n"
"                        const term = document.getElementById('terminal-output');\n"
"                        if (term) {\n"
"                            term.innerHTML += `<div><span style=\"color:#888\">[${new Date().toLocaleTimeString()}]</span> ${d.msg}</div>`;\n"
"                            term.scrollTop = term.scrollHeight;\n"
"                        }\n"
"                    }\n"
"                } catch(err) {}\n"
"            };\n"
"\n"
"        }\n"
"\n"
"        let lastX = 0, lastY = 0;\n"
"        let isTouching = false;\n"
"\n"
"        trackpad.addEventListener('touchstart', (e) => {\n"
"            isTouching = true;\n"
"            lastX = e.touches[0].clientX;\n"
"            lastY = e.touches[0].clientY;\n"
"        });\n"
"\n"
"        trackpad.addEventListener('touchmove', (e) => {\n"
"            if (!isTouching || ws.readyState !== WebSocket.OPEN) return;\n"
"            \n"
"            let curX = e.touches[0].clientX;\n"
"            let curY = e.touches[0].clientY;\n"
"            \n"
"            let dx = (curX - lastX) / 1.5;\n"
"            let dy = (curY - lastY) / 1.5;\n"
"            \n"
"            if (Math.abs(dx) > 0.5 || Math.abs(dy) > 0.5) {\n"
"                ws.send(JSON.stringify({ type: \"move\", dx: dx, dy: dy }));\n"
"                lastX = curX;\n"
"                lastY = curY;\n"
"            }\n"
"        });\n"
"\n"
"        trackpad.addEventListener('touchend', () => { isTouching = false; });\n"
"        trackpad.addEventListener('touchcancel', () => { isTouching = false; });\n"
"\n"
"        btnClick.addEventListener('click', (e) => { \n"
"            triggerHaptic(20);\n"
"            if(ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify({ type: \"click\" }));\n"
"        });\n"
"        \n"
"        btnBack.addEventListener('click', (e) => { \n"
"            triggerHaptic(20);\n"
"            if(ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify({ type: \"back\" }));\n"
"        });\n"
"\n"
"        document.getElementById('btn-r1').addEventListener('click', (e) => { \n"
"            triggerHaptic(20);\n"
"            if(ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify({ type: \"relay\", relay: 1 }));\n"
"        });\n"
"        document.getElementById('btn-r2').addEventListener('click', (e) => { \n"
"            triggerHaptic(20);\n"
"            if(ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify({ type: \"relay\", relay: 2 }));\n"
"        });\n"
"\n"
"        // Fallback for PC\n"
"        let isMouseDown = false;\n"
"        trackpad.addEventListener('mousedown', (e) => {\n"
"            isMouseDown = true;\n"
"            lastX = e.clientX; lastY = e.clientY;\n"
"        });\n"
"        trackpad.addEventListener('mousemove', (e) => {\n"
"            if (!isMouseDown || ws.readyState !== WebSocket.OPEN) return;\n"
"            let dx = (e.clientX - lastX) / 1.5; let dy = (e.clientY - lastY) / 1.5;\n"
"            if (Math.abs(dx) > 0.5 || Math.abs(dy) > 0.5) {\n"
"                ws.send(JSON.stringify({ type: \"move\", dx: dx, dy: dy }));\n"
"                lastX = e.clientX; lastY = e.clientY;\n"
"            }\n"
"        });\n"
"        trackpad.addEventListener('mouseup', () => { isMouseDown = false; });\n"
"        trackpad.addEventListener('mouseleave', () => { isMouseDown = false; });\n"
"        \n"
"        // Wallpaper Upload Logic\n"
"        const btnWp = document.getElementById('btn-wp');\n"
"        const fileInput = document.getElementById('file-input');\n"
"        \n"
"        btnWp.addEventListener('click', () => {\n"
"            fileInput.click();\n"
"        });\n"
"        \n"
"        fileInput.addEventListener('change', (e) => {\n"
"            const file = e.target.files[0];\n"
"            if (!file) return;\n"
"            \n"
"            statusEl.innerText = \"⏳ Đang xử lý ảnh...\";\n"
"            const reader = new FileReader();\n"
"            reader.onload = (event) => {\n"
"                const img = new Image();\n"
"                img.onload = () => {\n"
"                    const canvas = document.createElement('canvas');\n"
"                    canvas.width = 160;\n"
"                    canvas.height = 128;\n"
"                    const ctx = canvas.getContext('2d');\n"
"                    ctx.drawImage(img, 0, 0, 160, 128);\n"
"                    \n"
"                    const imageData = ctx.getImageData(0, 0, 160, 128);\n"
"                    const pixels = imageData.data;\n"
"                    const buffer = new ArrayBuffer(160 * 128 * 2);\n"
"                    const view = new DataView(buffer);\n"
"                    \n"
"                    let j = 0;\n"
"                    for (let i = 0; i < pixels.length; i += 4) {\n"
"                        const r = pixels[i] >> 3;\n"
"                        const g = pixels[i+1] >> 2;\n"
"                        const b = pixels[i+2] >> 3;\n"
"                        const rgb565 = (r << 11) | (g << 5) | b;\n"
"                        // Little-endian\n"
"                        view.setUint16(j, rgb565, true);\n"
"                        j += 2;\n"
"                    }\n"
"                    \n"
"                    statusEl.innerText = \"🚀 Đang gửi ảnh...\";\n"
"                    fetch('/upload_bg', {\n"
"                        method: 'POST',\n"
"                        body: buffer,\n"
"                        headers: {\n"
"                            'Content-Type': 'application/octet-stream'\n"
"                        }\n"
"                    }).then(res => {\n"
"                        if (res.ok) statusEl.innerText = \"✅ Đổi hình nền thành công!\";\n"
"                        else statusEl.innerText = \"❌ Lỗi khi gửi ảnh\";\n"
"                    }).catch(err => {\n"
"                        statusEl.innerText = \"❌ Lỗi kết nối\";\n"
"                    });\n"
"                };\n"
"                img.src = event.target.result;\n"
"            };\n"
"            reader.readAsDataURL(file);\n"
"        });\n"
"\n"
"        \n"
"        // Settings Logic\n"
"        function openSettings() {\n"
"            document.getElementById('settings-modal').style.display = 'flex';\n"
"            fetch('/api/settings').then(r=>r.json()).then(d=>{\n"
"                document.getElementById('chk-logCsv').checked = d.logCsv;\n"
"                document.getElementById('chk-ota').checked = d.ota;\n"
"                document.getElementById('chk-audio').checked = d.audio;\n"
"                document.getElementById('chk-popup').checked = d.popup;\n"
"            });\n"
"        }\n"
"        \n"
"\n"
"\n"
"        \n"
"        // File Manager Logic\n"
"        function openFM() {\n"
"            document.getElementById('fm-modal').style.display = 'flex';\n"
"            loadFiles();\n"
"        }\n"
"        function loadFiles() {\n"
"            fetch('/api/fs').then(r=>r.json()).then(d=>{\n"
"                const tbody = document.getElementById('fm-tbody');\n"
"                if(!tbody) return;\n"
"                tbody.innerHTML = '';\n"
"                d.files.forEach(f => {\n"
"                    const sizeKB = (f.size / 1024).toFixed(2);\n"
"                    tbody.innerHTML += `<tr style=\"border-bottom: 1px solid #eee;\">\n"
"                        <td style=\"padding: 10px; color: #333;\">${f.name}</td>\n"
"                        <td style=\"padding: 10px; color: #333;\">${sizeKB} KB</td>\n"
"                        <td style=\"padding: 10px;\">\n"
"                            <a href=\"${f.name}\" download style=\"background: #10b981; color: #fff; padding: 5px 10px; text-decoration: none; border-radius: 4px; margin-right: 5px; font-size: 14px;\">Tải</a>\n"
"                            <button onclick=\"deleteFile('${f.name}')\" style=\"background: #ef4444; color: #fff; padding: 5px 10px; border: none; border-radius: 4px; cursor: pointer; font-size: 14px;\">Xóa</button>\n"
"                        </td>\n"
"                    </tr>`;\n"
"                });\n"
"            });\n"
"        }\n"
"        function deleteFile(name) {\n"
"            if(confirm('Chắc chắn xóa ' + name + '?')) {\n"
"                fetch('/api/fs/delete', {\n"
"                    method: 'POST',\n"
"                    headers: {'Content-Type': 'application/json'},\n"
"                    body: JSON.stringify({filename: name})\n"
"                }).then(() => loadFiles());\n"
"            }\n"
"        }\n"
"\n"
"        \n"
"        window.onclick = function(event) {\n"
"            if (!event.target.matches('.dropbtn')) {\n"
"                var dropdowns = document.getElementsByClassName(\"dropdown-content\");\n"
"                for (var i = 0; i < dropdowns.length; i++) {\n"
"                    var openDropdown = dropdowns[i];\n"
"                    if (openDropdown.classList.contains('show')) {\n"
"                        openDropdown.classList.remove('show');\n"
"                    }\n"
"                }\n"
"            }\n"
"        }\n"
"\n"
"        // Chart.js Logic\n"
"        let myChart = null;\n"
"        function loadChartData() {\n"
"            fetch('/api/data')\n"
"            .then(res => res.json())\n"
"            .then(data => {\n"
"                if (data.ramFree && data.ramTotal) {\n"
"                    const rf = (data.ramFree / 1024).toFixed(1);\n"
"                    const rt = (data.ramTotal / 1024).toFixed(1);\n"
"                    document.getElementById('ram-info').innerText = `RAM Trống: ${rf} KB / ${rt} KB`;\n"
"                }\n"
"                if (data.outT !== undefined) {\n"
"                    let wInfo = `Ngoài trời: ${data.outT.toFixed(1)}°C | ${data.outH}%<br>`;\n"
"                    wInfo += `Trong nhà: ${data.inT.toFixed(1)}°C | ${data.inH}%<br>`;\n"
"                    wInfo += `AI: <span style=\"color: #64748b;\">${data.ai}</span>`;\n"
"                    document.getElementById('weather-info').innerHTML = wInfo;\n"
"                }\n"
"                \n"
"                const ctx = document.getElementById('dataChart').getContext('2d');\n"
"                const curH = data.curHour !== undefined ? data.curHour : new Date().getHours();\n"
"                const count = data.histT.length;\n"
"                const labels = data.histT.map((_, i) => {\n"
"                    let h = curH - (count - 1 - i);\n"
"                    if (h < 0) h += 24;\n"
"                    return h + \"h\";\n"
"                });\n"
"                \n"
"                if (myChart) {\n"
"                    myChart.data.labels = labels;\n"
"                    myChart.data.datasets[0].data = data.histT;\n"
"                    myChart.data.datasets[1].data = data.histH;\n"
"                    if(data.histOwmT) {\n"
"                        myChart.data.datasets[2].data = data.histOwmT;\n"
"                        myChart.data.datasets[3].data = data.histOwmH;\n"
"                    }\n"
"                    myChart.update();\n"
"                } else {\n"
"                    let datasets = [\n"
"                        { label: 'In Temp (C)', data: data.histT, borderColor: '#ef4444', tension: 0.3 },\n"
"                        { label: 'In Hum (%)', data: data.histH, borderColor: '#3b82f6', tension: 0.3 }\n"
"                    ];\n"
"                    if(data.histOwmT) {\n"
"                        datasets.push({ label: 'Out Temp (C)', data: data.histOwmT, borderColor: '#f97316', tension: 0.3, borderDash: [5, 5] });\n"
"                        datasets.push({ label: 'Out Hum (%)', data: data.histOwmH, borderColor: '#0ea5e9', tension: 0.3, borderDash: [5, 5] });\n"
"                    }\n"
"                    myChart = new Chart(ctx, {\n"
"                        type: 'line',\n"
"                        data: {\n"
"                            labels: labels,\n"
"                            datasets: datasets\n"
"                        },\n"
"                        options: {\n"
"                            responsive: true, maintainAspectRatio: false,\n"
"                            plugins: { legend: { labels: { color: '#4a5568' } } },\n"
"                            scales: {\n"
"                                x: { ticks: { color: '#4a5568' } },\n"
"                                y: { ticks: { color: '#4a5568' } }\n"
"                            }\n"
"                        }\n"
"                    });\n"
"                }\n"
"            })\n"
"            .catch(err => console.log(\"Chart fetch error\", err));\n"
"        }\n"
"\n"
"        window.onload = () => {\n"
"            ['logCsv', 'ota', 'audio', 'popup'].forEach(k => {\n"
"                document.getElementById('chk-'+k).addEventListener('change', () => {\n"
"                    const data = {\n"
"                        logCsv: document.getElementById('chk-logCsv').checked,\n"
"                        ota: document.getElementById('chk-ota').checked,\n"
"                        audio: document.getElementById('chk-audio').checked,\n"
"                        popup: document.getElementById('chk-popup').checked\n"
"                    };\n"
"                    fetch('/api/settings', {\n"
"                        method: 'POST',\n"
"                        headers: {'Content-Type': 'application/json'},\n"
"                        body: JSON.stringify(data)\n"
"                    });\n"
"                });\n"
"            });\n"
"            connectWs();\n"
"            loadChartData();\n"
"            setInterval(loadChartData, 10000); // Reload chart & RAM every 10 seconds\n"
"        };\n"
"    </script>\n"
"\n"
"    <!-- Settings Modal -->\n"
"    <div id=\"settings-modal\" class=\"modal\">\n"
"        <div class=\"modal-content\">\n"
"            <div class=\"modal-header\">Cài Đặt Hệ Thống</div>\n"
"            <div class=\"setting-item\">\n"
"                <span>Lưu log CSV (LittleFS)</span>\n"
"                <label class=\"switch\"><input type=\"checkbox\" id=\"chk-logCsv\"><span class=\"slider\"></span></label>\n"
"            </div>\n"
"            <div class=\"setting-item\">\n"
"                <span>Cập nhật qua Web (OTA)</span>\n"
"                <label class=\"switch\"><input type=\"checkbox\" id=\"chk-ota\"><span class=\"slider\"></span></label>\n"
"            </div>\n"
"            <div class=\"setting-item\">\n"
"                <span>Âm thanh cảnh báo</span>\n"
"                <label class=\"switch\"><input type=\"checkbox\" id=\"chk-audio\"><span class=\"slider\"></span></label>\n"
"            </div>\n"
"            <div class=\"setting-item\">\n"
"                <span>Pop-up trên màn hình</span>\n"
"                <label class=\"switch\"><input type=\"checkbox\" id=\"chk-popup\"><span class=\"slider\"></span></label>\n"
"            </div>\n"
"            <div style=\"display:flex; gap:10px; margin-top: 20px;\">\n"
"                <button class=\"close-btn\" onclick=\"document.getElementById('settings-modal').style.display='none'\">Đóng</button>\n"
"                <button class=\"close-btn\" style=\"background:#10b981;\" onclick=\"window.location.href='/download_csv'\">Tải CSV</button>\n"
"            </div>\n"
"            <div style=\"margin-top: 15px;\">\n"
"                <form method=\"POST\" action=\"/update\" enctype=\"multipart/form-data\" id=\"ota-form\">\n"
"                    <input type=\"file\" name=\"update\" style=\"width:100%; font-size: 12px;\">\n"
"                    <button type=\"submit\" class=\"close-btn\" style=\"background:#ef4444; margin-top:5px; padding:5px;\">Nạp Firmware OTA</button>\n"
"                </form>\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"\n"
"    <!-- Terminal Modal -->\n"
"    <div id=\"terminal-modal\" class=\"modal\">\n"
"        <div class=\"modal-content\" style=\"background: #1e1e1e; color: #00ff00; font-family: monospace; height: 80vh; width: 90%; max-width: 800px;\">\n"
"            <div class=\"modal-header\" style=\"color: #fff; border-bottom: 1px solid #333;\">Terminal Log</div>\n"
"            <div id=\"terminal-output\" style=\"overflow-y: auto; height: calc(100% - 120px); padding: 10px; text-align: left; white-space: pre-wrap; font-size: 14px;\"></div>\n"
"            <div style=\"display:flex; gap:10px; margin-top: 20px; justify-content: center;\">\n"
"                <button class=\"close-btn\" style=\"background:#555;\" onclick=\"document.getElementById('terminal-modal').style.display='none'\">Đóng</button>\n"
"                <button class=\"close-btn\" style=\"background:#d32f2f;\" onclick=\"document.getElementById('terminal-output').innerHTML=''\">Xóa Log</button>\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- File Manager Modal -->\n"
"    <div id=\"fm-modal\" class=\"modal\">\n"
"        <div class=\"modal-content\" style=\"width: 90%; max-width: 600px;\">\n"
"            <div class=\"modal-header\">Quản Lý File (LittleFS)</div>\n"
"            <div id=\"fm-list\" style=\"max-height: 50vh; overflow-y: auto; margin-bottom: 20px;\">\n"
"                <table style=\"width: 100%; border-collapse: collapse; text-align: left;\">\n"
"                    <thead>\n"
"                        <tr style=\"border-bottom: 2px solid #ddd;\">\n"
"                            <th style=\"padding: 10px; color: #555;\">Tên File</th>\n"
"                            <th style=\"padding: 10px; color: #555;\">Dung lượng</th>\n"
"                            <th style=\"padding: 10px; color: #555;\">Hành động</th>\n"
"                        </tr>\n"
"                    </thead>\n"
"                    <tbody id=\"fm-tbody\"></tbody>\n"
"                </table>\n"
"            </div>\n"
"            <div style=\"display:flex; justify-content: center; gap: 10px;\">\n"
"                <button class=\"close-btn\" onclick=\"document.getElementById('fm-modal').style.display='none'\">Đóng</button>\n"
"                <button class=\"close-btn\" style=\"background:#3b82f6;\" onclick=\"loadFiles()\">Làm mới</button>\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"</body>\n"
"</html>\n"
;

#endif
